//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fish.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spt_fallback_dev
    {
        public string xserver_name { get; set; }
        public System.DateTime xdttm_ins { get; set; }
        public System.DateTime xdttm_last_ins_upd { get; set; }
        public Nullable<int> xfallback_low { get; set; }
        public string xfallback_drive { get; set; }
        public int low { get; set; }
        public int high { get; set; }
        public short status { get; set; }
        public string name { get; set; }
        public string phyname { get; set; }
    }
}
