//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fish.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TaiwanFish
    {
        public int Id { get; set; }
        [DisplayName("魚類名稱")]
        public string Name { get; set; }
        [DisplayName("台灣分佈")]
        public string Taiwan_Distribution { get; set; }
        [DisplayName("棲息環境")]
        public string Habitat { get; set; }
        [DisplayName("最大體長")]
        public string Max_body_length { get; set; }
        [DisplayName("圖片")]
        public string Image_Path { get; set; }
    }
}
